server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hgx615/spring-cloud-config-repo      # 配置Git仓库的地址
          username: hgx615@126.com                                    # Git仓库的账号
          password: 123456                                        # Git仓库的密码